# This is language file. You can change it!
nick = 'Nick'
installed = 'Installed'
ready_to_install = 'Ready to install'
install_run = 'Run'
error = 'Error'
account = 'Account'
version = 'Version'
run = 'Run'
settings = 'Settings'
exit = 'Exit'
file = 'File'
version_is_not_detected = 'Invalid version'
mojang_login = 'Log in through Mojang'
ask_mojang_login = 'Enter Mojang login'
ask_mojang_password = 'Enter Mojang password'
error_during_login = 'Error! Login or Password is incorrect!'
